In [4]:
import torch
import numpy as np
np.set_printoptions(precision=3)
a = [1,2,3]
b = np.array([4,5,6], dtype=np.int32)
t_a = torch.tensor(a)
t_b = torch.from_numpy(b)
print(t_a)
print(t_b)


tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)


In [2]:
! pip install torch

   ---------------------------------------- 0.0/198.5 MB ? eta -:--:--
   ---------------------------------------- 0.4/198.5 MB 7.4 MB/s eta 0:00:27
   ---------------------------------------- 0.8/198.5 MB 8.4 MB/s eta 0:00:24
   ---------------------------------------- 1.3/198.5 MB 9.2 MB/s eta 0:00:22
   ---------------------------------------- 1.9/198.5 MB 9.9 MB/s eta 0:00:20
   ---------------------------------------- 2.4/198.5 MB 10.2 MB/s eta 0:00:20
    --------------------------------------- 3.0/198.5 MB 10.5 MB/s eta 0:00:19
    --------------------------------------- 3.5/198.5 MB 10.6 MB/s eta 0:00:19
    --------------------------------------- 4.1/198.5 MB 10.8 MB/s eta 0:00:19
    --------------------------------------- 4.6/198.5 MB 10.9 MB/s eta 0:00:18
   - -------------------------------------- 5.2/198.5 MB 11.0 MB/s eta 0:00:18
   - -------------------------------------- 5.7/198.5 MB 11.1 MB/s eta 0:00:18
   - -------------------------------------- 6.3/198.5 MB 11.1 MB

In [5]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(device)

cpu


In [6]:
t_ones = torch.ones((2, 3))

In [7]:
torch.manual_seed(0)

In [12]:
t1 = 2*torch.rand((5,2))-1
t2 = torch.normal(mean=0, std=1, size=(5,2))

In [14]:
t3 = torch.multiply(t1,t2)
t3

tensor([[-0.0654,  0.2442],
        [-0.1160,  1.4053],
        [-0.1842, -0.9301],
        [-0.2841, -0.2832],
        [-0.2917, -0.0339]])

In [15]:
t4 = torch.mean(t1, axis=1)
# 신기하게도 1일때 column의 평균을 구하고 0일때 row의 평균을 구한다.
t4

tensor([-0.2300, -0.3823, -0.6190,  0.6086, -0.2398])

In [16]:
t5 = torch.matmul(t1, torch.transpose(t2, 0, 1))
t5

tensor([[ 0.1788,  0.7356, -0.9116,  0.2240, -0.4466],
        [ 0.2344,  1.2893, -1.6415,  0.3748, -0.7651],
        [ 1.1435,  1.2716, -1.1144,  0.5743, -0.9591],
        [-1.0633, -1.3153,  1.2187, -0.5673,  0.9653],
        [ 0.5683,  0.3585, -0.1782,  0.2171, -0.3256]])

In [23]:
torch.manual_seed(1)

t = torch.rand(6)

print(t)

t_splits = torch.chunk(t, 3)


[item.numpy() for item in t_splits]

tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293, 0.7999])


[array([0.758, 0.279], dtype=float32),
 array([0.403, 0.735], dtype=float32),
 array([0.029, 0.8  ], dtype=float32)]