# Modeling4: 결측치 KNN

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# 데이터 불러오기
data_origin = pd.read_csv("https://raw.githubusercontent.com/agtechresearch/LectureAlgorithm/main/csv/married_full.csv")
data_origin

gender   age  age_partner  importance_same_religion  \
0     female  21.0         27.0                       4.0   
1     female  21.0         22.0                       4.0   
2     female  21.0         22.0                       4.0   
3     female  21.0         23.0                       4.0   
4     female  21.0         24.0                       4.0   
...      ...   ...          ...                       ...   
8357    male  25.0         26.0                       1.0   
8358    male  25.0         24.0                       1.0   
8359    male  25.0         29.0                       1.0   
8360    male  25.0         22.0                       1.0   
8361    male  25.0         22.0                       1.0   

      pref_of_partner_attractive  pref_of_partner_sincere  \
0                           35.0                     20.0   
1                           60.0                      0.0   
2                           19.0                     18.0   
3                           30.0                      5.0   
4                           30.0                     10.0   
...                          ...                      ...   
8357                        10.0                     10.0   
8358                        50.0                     20.0   
8359                        40.0                     10.0   
8360                        10.0                     25.0   
8361                        20.0                     20.0   

      pref_of_partner_intelligence  pref_of_partner_funny  \
0                             20.0                   20.0   
1                              0.0                   40.0   
2                             19.0                   18.0   
3                             15.0                   40.0   
4                             20.0                   10.0   
...                            ...                    ...   
8357                          30.0                   20.0   
8358                          10.0                    5.0   
8359                          30.0                   10.0   
8360                          25.0                   10.0   
8361                          10.0                   15.0   

      pref_of_partner_ambitious  pref_of_partner_shared_interests  ...  \
0                           0.0                               5.0  ...   
1                           0.0                               0.0  ...   
2                          14.0                              12.0  ...   
3                           5.0                               5.0  ...   
4                          10.0                              20.0  ...   
...                         ...                               ...  ...   
8357                       10.0                              15.0  ...   
8358                       10.0                               5.0  ...   
8359                       10.0                               NaN  ...   
8360                       10.0                              20.0  ...   
8361                        5.0                              30.0  ...   

      my_eval_sincere  my_eval_intelligence  my_eval_funny  my_eval_ambition  \
0                 9.0                   7.0            7.0               6.0   
1                 8.0                   7.0            8.0               5.0   
2                 8.0                   9.0            8.0               5.0   
3                 6.0                   8.0            7.0               6.0   
4                 6.0                   7.0            7.0               6.0   
...               ...                   ...            ...               ...   
8357              5.0                   5.0            5.0               NaN   
8358              6.0                   8.0            4.0               4.0   
8359              7.0                   8.0            8.0               8.0   
8360              6.0                   5.0            4.0               NaN   
8361              7.0                 

In [3]:
# 전처리를 위한 원본 데이터 복사
data = data_origin.copy()

In [4]:
# 메모리를 효율적으로 사용하기 위한 downcast 함수 정의
def downcast(df, verbose=True):     # verbose 옵션 추가: (True)인 경우 몇 퍼센트 압축됐는지 출력
    start_mem = df.memory_usage().sum() / 1024**2   # 초기 메모리 사용량
    for col in df.columns:
        dtype_name = df[col].dtype.name
        if dtype_name == 'object':
            pass
        elif dtype_name == 'bool':
            df[col] = df[col].astype('int8')
        elif dtype_name.startswith('int') or (df[col].round() == df[col]).all():
            df[col] = pd.to_numeric(df[col], downcast='integer')
        else:
            df[col] = pd.to_numeric(df[col], downcast='float')
    end_mem = df.memory_usage().sum() / 1024**2

    if verbose:
        print(f'{(100*(start_mem - end_mem) / start_mem):.1f}% 압축됨')

    return df

In [5]:
downcast(data)

49.6% 압축됨


gender   age  age_partner  importance_same_religion  \
0     female  21.0         27.0                       4.0   
1     female  21.0         22.0                       4.0   
2     female  21.0         22.0                       4.0   
3     female  21.0         23.0                       4.0   
4     female  21.0         24.0                       4.0   
...      ...   ...          ...                       ...   
8357    male  25.0         26.0                       1.0   
8358    male  25.0         24.0                       1.0   
8359    male  25.0         29.0                       1.0   
8360    male  25.0         22.0                       1.0   
8361    male  25.0         22.0                       1.0   

      pref_of_partner_attractive  pref_of_partner_sincere  \
0                           35.0                     20.0   
1                           60.0                      0.0   
2                           19.0                     18.0   
3                           30.0                      5.0   
4                           30.0                     10.0   
...                          ...                      ...   
8357                        10.0                     10.0   
8358                        50.0                     20.0   
8359                        40.0                     10.0   
8360                        10.0                     25.0   
8361                        20.0                     20.0   

      pref_of_partner_intelligence  pref_of_partner_funny  \
0                             20.0                   20.0   
1                              0.0                   40.0   
2                             19.0                   18.0   
3                             15.0                   40.0   
4                             20.0                   10.0   
...                            ...                    ...   
8357                          30.0                   20.0   
8358                          10.0                    5.0   
8359                          30.0                   10.0   
8360                          25.0                   10.0   
8361                          10.0                   15.0   

      pref_of_partner_ambitious  pref_of_partner_shared_interests  ...  \
0                           0.0                               5.0  ...   
1                           0.0                               0.0  ...   
2                          14.0                              12.0  ...   
3                           5.0                               5.0  ...   
4                          10.0                              20.0  ...   
...                         ...                               ...  ...   
8357                       10.0                              15.0  ...   
8358                       10.0                               5.0  ...   
8359                       10.0                               NaN  ...   
8360                       10.0                              20.0  ...   
8361                        5.0                              30.0  ...   

      my_eval_sincere  my_eval_intelligence  my_eval_funny  my_eval_ambition  \
0                 9.0                   7.0            7.0               6.0   
1                 8.0                   7.0            8.0               5.0   
2                 8.0                   9.0            8.0               5.0   
3                 6.0                   8.0            7.0               6.0   
4                 6.0                   7.0            7.0               6.0   
...               ...                   ...            ...               ...   
8357              5.0                   5.0            5.0               NaN   
8358              6.0                   8.0            4.0               4.0   
8359              7.0                   8.0            8.0               8.0   
8360              6.0                   5.0            4.0               NaN   
8361              7.0                 

> Train/Test data split

In [6]:
# 단순 랜덤 샘플링
#from sklearn.model_selection import train_test_split

#train_set, test_set = train_test_split(data, test_size = 0.2, random_state=42)


# 계층적 샘플링
from sklearn.model_selection import StratifiedShuffleSplit

split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in split.split(data, data['married']):
    sss_train_set = data.loc[train_index]
    sss_test_set = data.loc[test_index]

In [7]:
X_train = sss_train_set.drop("married", axis=1)
y_train = sss_train_set["married"].copy()

X_test = sss_test_set.drop("married", axis=1)
y_test = sss_test_set["married"].copy()

# Preprocessing

> 전처리 process 정리
> 1. 결측치 채우기(KNN)
> 2. 수치형 변수 표준화(Standardization)
> 3. 범주형 변수 OneHotEncoding
> 4. SMOTE-Tomek 오버샘플링

In [9]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

num_attribs = X_train.columns[1:]     # 수치형 column 지정
cat_attribs = ['gender']    # 범주형 column 지정

# 수치형 변수 파이프라인
num_pipeline = Pipeline([
    ('imputer', IterativeImputer(random_state=42)),             # KNN 기반 결측치 처리
    ('std_scaler', StandardScaler()),                   # 표준화
])

# 전체 전처리 파이프라인
full_pipeline = ColumnTransformer([
    ('num', num_pipeline, num_attribs),                 # 수치형 변수 파이프라인 적용
    ('cat', OneHotEncoder(drop='first'), cat_attribs),  # 범주형 변수 OHE 적용
])

X_train_scaled = full_pipeline.fit_transform(X_train)

c:\Users\prohe\anaconda3\envs\py38\lib\site-packages\sklearn\impute\_iterative.py:796: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(


In [10]:
# SMOTE-Tomek 샘플링
from imblearn.combine import SMOTETomek
from imblearn.under_sampling import TomekLinks

smoteto = SMOTETomek(tomek=TomekLinks(sampling_strategy='majority'))
X_resampled, y_resampled = smoteto.fit_resample(X_train_scaled, y_train)

In [11]:
X_resampled.shape, y_resampled.shape

((10951, 32), (10951,))

> 기본적인 데이터셋 준비 완료

# Model Training

In [11]:
# lightgbm 모델 학습
from lightgbm import LGBMClassifier

params = {
    'n_estimators': 300,        #* 반복 수행하려는 트리의 개수 (너무 크면 오버피팅 발생)
    'max_depth': 8,             #* 트리의 최대 깊이 (너무 크면 오버피팅 발생)   # 보통 3~12(가장 민감하므로 먼저 튜닝해야할 값) # lightgbm처럼 leaf-wise로 학습하는 경우 끝까지(-1)도 괜찮다고 한다.
    # 'boosting_type' = 'gbdt'  # 부스팅 타입 (gbdt: Gradient Boosting Decision Tree, rf: RandomForest)
    'num_leaves': 16,           #* 하나의 트리가 가질 수 있는 최대 리프 수 (2번째로 민감. max_depth와 함께 튜닝)
    'learning_rate': 0.1,       # 부스팅 스탭 반복할 때 학습률(0~1) #튜닝시 0.1~0.3, 최종 모형은 0.05 이하
}

lgbm = LGBMClassifier(**params, objective='binary', metric='accuracy', random_state=42, verbose=0)
lgbm.fit(X_train_scaled, y_train)

LGBMClassifier(max_depth=8, metric='accuracy', n_estimators=300, num_leaves=16,
               objective='binary', random_state=42, verbose=0)

In [12]:
# Train data 성능 평가
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

y_train_pred = lgbm.predict(X_train_scaled)
print("<<Train Set Performance>>")
print("Accuracy: ", accuracy_score(y_train, y_train_pred))
print("F1 Score: ", f1_score(y_train, y_train_pred))
print(confusion_matrix(y_train, y_train_pred))

<<Train Set Performance>>
Accuracy:  0.9823590970249664
F1 Score:  0.9491817398794143
[[5469   10]
 [ 108 1102]]


In [13]:
# Test data 전처리
X_test_scaled = full_pipeline.transform(X_test)

In [15]:
X_test_scaled

array([[-0.6647712 ,  1.31485963,  0.84479266, ..., -2.26916718,
        -2.00827265,  0.        ],
       [ 0.74565619,  3.56241226, -0.58516067, ...,  0.46771714,
         0.84500188,  0.        ],
       [ 0.74565619,  0.47202721, -0.58516067, ..., -0.62703663,
        -1.05718112,  1.        ],
       ...,
       [-0.6647712 , -0.37080505,  1.202281  , ...,  1.01509404,
         0.84500188,  1.        ],
       [ 0.74565619,  1.0339154 , -0.94264907, ..., -0.07965975,
        -0.10608957,  1.        ],
       [-0.6647712 ,  0.19108315, -0.94264907, ..., -0.62703663,
        -0.10608957,  1.        ]])

In [14]:
# Test data 성능 평가
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

y_test_pred = lgbm.predict(X_test_scaled)
print("<<Test Set Performance>>")
print("Accuracy: ", accuracy_score(y_test, y_test_pred))
print("F1 Score: ", f1_score(y_test, y_test_pred))
print(confusion_matrix(y_test, y_test_pred))

<<Test Set Performance>>
Accuracy:  0.8487746563060371
F1 Score:  0.4929859719438878
[[1297   73]
 [ 180  123]]


### lightGBM 가중치 조정
> lightGBM에는 소수 class에 가중치를 주는 하이퍼파라미터가 있다. 이를 사용해보자.

In [16]:
# lightgbm 모델 학습
from lightgbm import LGBMClassifier

params = {
    'n_estimators': 300,        #* 반복 수행하려는 트리의 개수 (너무 크면 오버피팅 발생)
    'max_depth': 8,             #* 트리의 최대 깊이 (너무 크면 오버피팅 발생)   # 보통 3~12(가장 민감하므로 먼저 튜닝해야할 값) # lightgbm처럼 leaf-wise로 학습하는 경우 끝까지(-1)도 괜찮다고 한다.
    # 'boosting_type' = 'gbdt'  # 부스팅 타입 (gbdt: Gradient Boosting Decision Tree, rf: RandomForest)
    'num_leaves': 16,           #* 하나의 트리가 가질 수 있는 최대 리프 수 (2번째로 민감. max_depth와 함께 튜닝)
    'learning_rate': 0.1,       # 부스팅 스탭 반복할 때 학습률(0~1) #튜닝시 0.1~0.3, 최종 모형은 0.05 이하
    'scale_pos_weight': 2       #* 불균형 데이터셋일 때, 1보다 높은 값으로 설정
}

lgbm = LGBMClassifier(**params, objective='binary', metric='accuracy', random_state=42, verbose=0)
lgbm.fit(X_train_scaled, y_train)

LGBMClassifier(max_depth=8, metric='accuracy', n_estimators=300, num_leaves=16,
               objective='binary', random_state=42, scale_pos_weight=2,
               verbose=0)

In [17]:
# Train data 성능 평가
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

y_train_pred = lgbm.predict(X_train_scaled)
print("<<Train Set Performance>>")
print("Accuracy: ", accuracy_score(y_train, y_train_pred))
print("F1 Score: ", f1_score(y_train, y_train_pred))
print(confusion_matrix(y_train, y_train_pred))

<<Train Set Performance>>
Accuracy:  0.9878905666018837
F1 Score:  0.9668711656441719
[[5426   53]
 [  28 1182]]


In [18]:
# Test data 성능 평가
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

y_test_pred = lgbm.predict(X_test_scaled)
print("<<Test Set Performance>>")
print("Accuracy: ", accuracy_score(y_test, y_test_pred))
print("F1 Score: ", f1_score(y_test, y_test_pred))
print(confusion_matrix(y_test, y_test_pred))

<<Test Set Performance>>
Accuracy:  0.8499701135684399
F1 Score:  0.5634782608695652
[[1260  110]
 [ 141  162]]
