In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# 데이터 불러오기
data_origin = pd.read_csv("https://raw.githubusercontent.com/agtechresearch/LectureAlgorithm/main/csv/married_full.csv")
data_origin

gender   age  age_partner  importance_same_religion  \
0     female  21.0         27.0                       4.0   
1     female  21.0         22.0                       4.0   
2     female  21.0         22.0                       4.0   
3     female  21.0         23.0                       4.0   
4     female  21.0         24.0                       4.0   
...      ...   ...          ...                       ...   
8357    male  25.0         26.0                       1.0   
8358    male  25.0         24.0                       1.0   
8359    male  25.0         29.0                       1.0   
8360    male  25.0         22.0                       1.0   
8361    male  25.0         22.0                       1.0   

      pref_of_partner_attractive  pref_of_partner_sincere  \
0                           35.0                     20.0   
1                           60.0                      0.0   
2                           19.0                     18.0   
3                           30.0                      5.0   
4                           30.0                     10.0   
...                          ...                      ...   
8357                        10.0                     10.0   
8358                        50.0                     20.0   
8359                        40.0                     10.0   
8360                        10.0                     25.0   
8361                        20.0                     20.0   

      pref_of_partner_intelligence  pref_of_partner_funny  \
0                             20.0                   20.0   
1                              0.0                   40.0   
2                             19.0                   18.0   
3                             15.0                   40.0   
4                             20.0                   10.0   
...                            ...                    ...   
8357                          30.0                   20.0   
8358                          10.0                    5.0   
8359                          30.0                   10.0   
8360                          25.0                   10.0   
8361                          10.0                   15.0   

      pref_of_partner_ambitious  pref_of_partner_shared_interests  ...  \
0                           0.0                               5.0  ...   
1                           0.0                               0.0  ...   
2                          14.0                              12.0  ...   
3                           5.0                               5.0  ...   
4                          10.0                              20.0  ...   
...                         ...                               ...  ...   
8357                       10.0                              15.0  ...   
8358                       10.0                               5.0  ...   
8359                       10.0                               NaN  ...   
8360                       10.0                              20.0  ...   
8361                        5.0                              30.0  ...   

      my_eval_sincere  my_eval_intelligence  my_eval_funny  my_eval_ambition  \
0                 9.0                   7.0            7.0               6.0   
1                 8.0                   7.0            8.0               5.0   
2                 8.0                   9.0            8.0               5.0   
3                 6.0                   8.0            7.0               6.0   
4                 6.0                   7.0            7.0               6.0   
...               ...                   ...            ...               ...   
8357              5.0                   5.0            5.0               NaN   
8358              6.0                   8.0            4.0               4.0   
8359              7.0                   8.0            8.0               8.0   
8360              6.0                   5.0            4.0               NaN   
8361              7.0                 

In [3]:
# 전처리를 위한 원본 데이터 복사
data = data_origin.copy()

In [4]:
# 메모리를 효율적으로 사용하기 위한 downcast 함수 정의
def downcast(df, verbose=True):     # verbose 옵션 추가: (True)인 경우 몇 퍼센트 압축됐는지 출력
    start_mem = df.memory_usage().sum() / 1024**2   # 초기 메모리 사용량
    for col in df.columns:
        dtype_name = df[col].dtype.name
        if dtype_name == 'object':
            pass
        elif dtype_name == 'bool':
            df[col] = df[col].astype('int8')
        elif dtype_name.startswith('int') or (df[col].round() == df[col]).all():
            df[col] = pd.to_numeric(df[col], downcast='integer')
        else:
            df[col] = pd.to_numeric(df[col], downcast='float')
    end_mem = df.memory_usage().sum() / 1024**2

    if verbose:
        print(f'{(100*(start_mem - end_mem) / start_mem):.1f}% 압축됨')

    return df

In [5]:
downcast(data)

49.6% 압축됨


gender   age  age_partner  importance_same_religion  \
0     female  21.0         27.0                       4.0   
1     female  21.0         22.0                       4.0   
2     female  21.0         22.0                       4.0   
3     female  21.0         23.0                       4.0   
4     female  21.0         24.0                       4.0   
...      ...   ...          ...                       ...   
8357    male  25.0         26.0                       1.0   
8358    male  25.0         24.0                       1.0   
8359    male  25.0         29.0                       1.0   
8360    male  25.0         22.0                       1.0   
8361    male  25.0         22.0                       1.0   

      pref_of_partner_attractive  pref_of_partner_sincere  \
0                           35.0                     20.0   
1                           60.0                      0.0   
2                           19.0                     18.0   
3                           30.0                      5.0   
4                           30.0                     10.0   
...                          ...                      ...   
8357                        10.0                     10.0   
8358                        50.0                     20.0   
8359                        40.0                     10.0   
8360                        10.0                     25.0   
8361                        20.0                     20.0   

      pref_of_partner_intelligence  pref_of_partner_funny  \
0                             20.0                   20.0   
1                              0.0                   40.0   
2                             19.0                   18.0   
3                             15.0                   40.0   
4                             20.0                   10.0   
...                            ...                    ...   
8357                          30.0                   20.0   
8358                          10.0                    5.0   
8359                          30.0                   10.0   
8360                          25.0                   10.0   
8361                          10.0                   15.0   

      pref_of_partner_ambitious  pref_of_partner_shared_interests  ...  \
0                           0.0                               5.0  ...   
1                           0.0                               0.0  ...   
2                          14.0                              12.0  ...   
3                           5.0                               5.0  ...   
4                          10.0                              20.0  ...   
...                         ...                               ...  ...   
8357                       10.0                              15.0  ...   
8358                       10.0                               5.0  ...   
8359                       10.0                               NaN  ...   
8360                       10.0                              20.0  ...   
8361                        5.0                              30.0  ...   

      my_eval_sincere  my_eval_intelligence  my_eval_funny  my_eval_ambition  \
0                 9.0                   7.0            7.0               6.0   
1                 8.0                   7.0            8.0               5.0   
2                 8.0                   9.0            8.0               5.0   
3                 6.0                   8.0            7.0               6.0   
4                 6.0                   7.0            7.0               6.0   
...               ...                   ...            ...               ...   
8357              5.0                   5.0            5.0               NaN   
8358              6.0                   8.0            4.0               4.0   
8359              7.0                   8.0            8.0               8.0   
8360              6.0                   5.0            4.0               NaN   
8361              7.0                 

In [6]:
select_columns = ['eval_by_partner_attractive','eval_by_partner_sincere','eval_by_partner_intelligence','eval_by_partner_funny','eval_by_partner_ambitous','eval_by_partner_shared_interests',
                 'my_eval_attractive','my_eval_sincere','my_eval_intelligence','my_eval_funny','my_eval_ambition','my_eval_shared_interests','how_much_i_liked','guess_prob_liked','married']
selected_data = data[select_columns]

In [7]:
selected_data

eval_by_partner_attractive  eval_by_partner_sincere  \
0                            6.0                      8.0   
1                            7.0                      8.0   
2                           10.0                     10.0   
3                            7.0                      8.0   
4                            8.0                      7.0   
...                          ...                      ...   
8357                        10.0                      5.0   
8358                         6.0                      3.0   
8359                         2.0                      1.0   
8360                         5.0                      7.0   
8361                         8.0                      8.0   

      eval_by_partner_intelligence  eval_by_partner_funny  \
0                              8.0                    8.0   
1                             10.0                    7.0   
2                             10.0                   10.0   
3                              9.0                    8.0   
4                              9.0                    6.0   
...                            ...                    ...   
8357                           3.0                    2.0   
8358                           7.0                    3.0   
8359                           2.0                    2.0   
8360                           5.0                    5.0   
8361                           7.0                    7.0   

      eval_by_partner_ambitous  eval_by_partner_shared_interests  \
0                          8.0                               6.0   
1                          7.0                               5.0   
2                         10.0                              10.0   
3                          9.0                               8.0   
4                          9.0                               7.0   
...                        ...                               ...   
8357                       6.0                               5.0   
8358                       7.0                               2.0   
8359                       2.0                               1.0   
8360                       3.0                               6.0   
8361                       7.0                               7.0   

      my_eval_attractive  my_eval_sincere  my_eval_intelligence  \
0                    6.0              9.0                   7.0   
1                    7.0              8.0                   7.0   
2                    5.0              8.0                   9.0   
3                    7.0              6.0                   8.0   
4                    5.0              6.0                   7.0   
...                  ...              ...                   ...   
8357                 3.0              5.0                   5.0   
8358                 4.0              6.0                   8.0   
8359                 4.0              7.0                   8.0   
8360                 4.0              6.0                   5.0   
8361                 3.0              7.0                   6.0   

      my_eval_funny  my_eval_ambition  my_eval_shared_interests  \
0               7.0               6.0                       5.0   
1               8.0               5.0                       6.0   
2               8.0               5.0                       7.0   
3               7.0               6.0                       8.0   
4               7.0               6.0                       6.0   
...             ...               ...                       ...   
8357            5.0               NaN                       NaN   
8358            4.0               4.0                       NaN   
8359            8.0               8.0                       NaN   
8360            4.0               NaN                       5.0   
8361            4.0               8.0                       1.0   

      how_much_i_liked  guess_prob_liked  married  
0                  7.0               6.0        0  
1        

> Train/Test data split

In [8]:
# 단순 랜덤 샘플링
#from sklearn.model_selection import train_test_split

#train_set, test_set = train_test_split(data, test_size = 0.2, random_state=42)


# 계층적 샘플링
from sklearn.model_selection import StratifiedShuffleSplit

split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in split.split(selected_data, selected_data['married']):
    sss_train_set = selected_data.loc[train_index]
    sss_test_set = selected_data.loc[test_index]

In [9]:
X_train = sss_train_set.drop("married", axis=1)
y_train = sss_train_set["married"].copy()

X_test = sss_test_set.drop("married", axis=1)
y_test = sss_test_set["married"].copy()

# Preprocessing

> 전처리 process 정리
> 1. 결측치 채우기(임의로 중앙값)
> 2. 수치형 변수 표준화(Standardization)
> 3. 범주형 변수 OneHotEncoding
> 4. SMOTE-Tomek 오버샘플링

In [10]:
# KNN 결측치 대체
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=5)

X_train_imputed = imputer.fit_transform(X_train)
X_train_imputed = pd.DataFrame(X_train_imputed, columns=X_train.columns)

X_test_imputed = imputer.transform(X_test)
X_test_imputed = pd.DataFrame(X_test_imputed, columns=X_test.columns)

### Scaling

In [11]:
# scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_imputed)

X_test_scaled = scaler.transform(X_test_imputed)

In [12]:
X_train_scaled

array([[ 0.43059608, -0.09442975, -0.23336686, ..., -2.1913114 ,
        -1.1805166 , -1.5392374 ],
       [ 0.43059608, -1.2505767 , -0.23336686, ..., -0.24570255,
        -0.07810568, -0.58315355],
       [-1.1313764 ,  1.6397908 ,  1.73052   , ...,  0.24069966,
        -0.07810568, -0.10511161],
       ...,
       [-0.61071897, -1.2505767 , -1.5426248 , ...,  0.72710186,
         0.47309977,  0.85097224],
       [-0.09006141,  1.0617173 ,  0.42126212, ..., -1.2185069 ,
        -0.07810568,  0.37293035],
       [-2.1726916 , -2.4067237 , -2.1972537 , ..., -0.24570255,
        -0.07810568, -0.58315355]], dtype=float32)

### Over-Sampling

In [17]:
# SMOTE-Tomek 샘플링
from imblearn.combine import SMOTETomek
from imblearn.under_sampling import TomekLinks

smoteto = SMOTETomek(tomek=TomekLinks(sampling_strategy='majority'))
X_resampled, y_resampled = smoteto.fit_resample(X_train_scaled, y_train)

In [18]:
X_resampled.shape, y_resampled.shape

((10949, 14), (10949,))

> 기본적인 데이터셋 준비 완료

# Model Training

### LighGBM

In [23]:
# 베이지안 최적화
from lightgbm import LGBMClassifier
from sklearn.metrics import accuracy_score

param_bounds = {
    'n_estimators': (100, 500),
    'max_depth': (3, 10),
    'num_leaves': (20, 100),
    'min_child_samples': (10, 30),
    'learning_rate': (0.01, 0.3),
    'scale_pos_weight': (1, 2),
}

def eval_function(n_estimators, max_depth, num_leaves, min_child_samples, learning_rate, scale_pos_weight):
    params = {
        'n_estimators': int(n_estimators),
        'max_depth': int(max_depth),
        'num_leaves': int(num_leaves),
        'min_child_samples': int(min_child_samples),
        'learning_rate': learning_rate,
        'scale_pos_weight': scale_pos_weight,
    }
    lgbm = LGBMClassifier(**params, objective='binary', metric='accuracy', random_state=42, verbose=0)

    lgbm.fit(X_train_scaled, y_train)
    y_pred = lgbm.predict(X_test_scaled)
    acc = accuracy_score(y_test, y_pred)
    return acc

In [24]:
from bayes_opt import BayesianOptimization

optimizer = BayesianOptimization(f=eval_function, pbounds=param_bounds, random_state=42)
optimizer.maximize(init_points=5, n_iter=10)

|   iter    |  target   | learni... | max_depth | min_ch... | n_esti... | num_le... | scale_... |
-------------------------------------------------------------------------------------------------
| 1         | 0.8243    | 0.1186    | 9.655     | 24.64     | 339.5     | 32.48     | 1.156     |
| 2         | 0.8195    | 0.02684   | 9.063     | 22.02     | 383.2     | 21.65     | 1.97      |
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGB

In [25]:
# 최적화된 하이퍼파라미터로 모델 재학습
best_params = {
    'n_estimators': round(optimizer.max['params']['n_estimators']),
    'max_depth': round(optimizer.max['params']['max_depth']),
    'num_leaves': round(optimizer.max['params']['num_leaves']),
    'min_child_samples': round(optimizer.max['params']['min_child_samples']),
    'learning_rate': optimizer.max['params']['learning_rate'],
    'scale_pos_weight': optimizer.max['params']['scale_pos_weight'],
}

best_lgbm = LGBMClassifier(**best_params, objective='binary', metric='accuracy', random_state=42, verbose=0)
best_lgbm.fit(X_train_scaled, y_train)

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


LGBMClassifier(learning_rate=0.25362638707551943, max_depth=9,
               metric='accuracy', min_child_samples=13, n_estimators=301,
               num_leaves=63, objective='binary', random_state=42,
               scale_pos_weight=1.7559382302667341, verbose=0)

In [26]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

# Train data 성능 평가
y_train_pred = best_lgbm.predict(X_train_scaled)
print("<<Train Set Performance>>")
print("Accuracy: ", accuracy_score(y_train, y_train_pred))
print("F1 Score: ", f1_score(y_train, y_train_pred))
print(confusion_matrix(y_train, y_train_pred))

# Test data 성능 평가
y_test_pred = best_lgbm.predict(X_test_scaled)
print("<<Test Set Performance>>")
print("Accuracy: ", accuracy_score(y_test, y_test_pred))
print("F1 Score: ", f1_score(y_test, y_test_pred))
print(confusion_matrix(y_test, y_test_pred))

<<Train Set Performance>>
Accuracy:  0.9992525041112273
F1 Score:  0.9979381443298969
[[5474    5]
 [   0 1210]]
<<Test Set Performance>>
Accuracy:  0.826658696951584
F1 Score:  0.45895522388059706
[[1260  110]
 [ 180  123]]


### XGBoost

In [22]:
import xgboost as xgb

xgb_model = xgb.XGBClassifier(n_estimators=500, max_depth=5, random_state=100)
xgb_model.fit(X_train_scaled, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=500, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=100, ...)

In [23]:
# Train data 성능 평가
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

y_train_pred = xgb_model.predict(X_train_scaled)
print("<<Train Set Performance>>")
print("Accuracy: ", accuracy_score(y_train, y_train_pred))
print("F1 Score: ", f1_score(y_train, y_train_pred))
print(confusion_matrix(y_train, y_train_pred))

# Test data 성능 평가
y_test_pred = xgb_model.predict(X_test_scaled)
print("<<Test Set Performance>>")
print("Accuracy: ", accuracy_score(y_test, y_test_pred))
print("F1 Score: ", f1_score(y_test, y_test_pred))
print(confusion_matrix(y_test, y_test_pred))

<<Train Set Performance>>
Accuracy:  1.0
F1 Score:  1.0
[[5479    0]
 [   0 1210]]
<<Test Set Performance>>
Accuracy:  0.8487746563060371
F1 Score:  0.5235404896421846
[[1281   89]
 [ 164  139]]


### Random Forest

In [79]:
# rf 모델 학습
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=500, max_depth=10, random_state=42, class_weight='balanced')
rf.fit(X_train_scaled, y_train)

RandomForestClassifier(class_weight='balanced', max_depth=10, n_estimators=500,
                       random_state=42)

In [80]:
# Train data 성능 평가
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

y_train_pred = rf.predict(X_train_scaled)
print("<<Train Set Performance>>")
print("Accuracy: ", accuracy_score(y_train, y_train_pred))
print("F1 Score: ", f1_score(y_train, y_train_pred))
print(confusion_matrix(y_train, y_train_pred))

<<Train Set Performance>>
Accuracy:  0.9041710270593512
F1 Score:  0.775952464173366
[[4938  541]
 [ 100 1110]]


In [81]:
# Test data 성능 평가
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

y_test_pred = rf.predict(X_test_scaled)
print("<<Test Set Performance>>")
print("Accuracy: ", accuracy_score(y_test, y_test_pred))
print("F1 Score: ", f1_score(y_test, y_test_pred))
print(confusion_matrix(y_test, y_test_pred))

<<Test Set Performance>>
Accuracy:  0.8158995815899581
F1 Score:  0.5497076023391813
[[1177  193]
 [ 115  188]]


### SVC

In [17]:
# svc 모델 학습
from sklearn.svm import SVC

svc = SVC(kernel='rbf', C=10, gamma='scale', class_weight='balanced', random_state=42)
svc.fit(X_train_scaled, y_train)

SVC(C=10, class_weight='balanced', random_state=42)

In [19]:
# 베이지안 최적화
param_bounds = {
    'C': (0.1, 10),
    'gamma': (0.1, 10),
    }

def eval_function(C, gamma):

    svc = SVC(kernel='rbf', C=C, gamma=gamma, class_weight='balanced', random_state=42)
    svc.fit(X_train_scaled, y_train)
    y_pred = svc.predict(X_test_scaled)
    acc = accuracy_score(y_test, y_pred)
    return acc

In [20]:
from bayes_opt import BayesianOptimization

optimizer = BayesianOptimization(f=eval_function, pbounds=param_bounds, random_state=42)
optimizer.maximize(init_points=5, n_iter=10)

|   iter    |  target   |     C     |   gamma   |
-------------------------------------------------
| 1         | 0.8231    | 3.808     | 9.512     |
| 2         | 0.8452    | 7.347     | 6.027     |
| 3         | 0.8016    | 1.645     | 1.644     |
| 4         | 0.8296    | 0.675     | 8.675     |
| 5         | 0.8422    | 6.051     | 7.11      |
| 6         | 0.8279    | 10.0      | 8.6       |
| 7         | 0.8482    | 9.615     | 2.971     |
| 8         | 0.7663    | 10.0      | 0.1       |
| 9         | 0.8524    | 8.79      | 4.174     |
| 10        | 0.8494    | 6.361     | 3.621     |
| 11        | 0.8458    | 4.21      | 5.238     |
| 12        | 0.8458    | 9.991     | 5.358     |
| 13        | 0.8213    | 0.1       | 5.582     |
| 14        | 0.8219    | 7.269     | 10.0      |
| 15        | 0.8033    | 5.495     | 1.249     |


In [21]:
# 최적화된 하이퍼파라미터로 모델 재학습
best_params = optimizer.max['params']

best_svc = SVC(**best_params, kernel='rbf', class_weight='balanced', random_state=42)
best_svc.fit(X_train_scaled, y_train)

SVC(C=8.789611237971195, class_weight='balanced', gamma=4.174215475911348,
    random_state=42)

In [22]:
# Train data 성능 평가
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

y_train_pred = best_svc.predict(X_train_scaled)
print("<<Train Set Performance>>")
print("Accuracy: ", accuracy_score(y_train, y_train_pred))
print("F1 Score: ", f1_score(y_train, y_train_pred))
print(confusion_matrix(y_train, y_train_pred))

# Test data 성능 평가
y_test_pred = best_svc.predict(X_test_scaled)
print("<<Test Set Performance>>")
print("Accuracy: ", accuracy_score(y_test, y_test_pred))
print("F1 Score: ", f1_score(y_test, y_test_pred))
print(confusion_matrix(y_test, y_test_pred))

<<Train Set Performance>>
Accuracy:  1.0
F1 Score:  1.0
[[5479    0]
 [   0 1210]]
<<Test Set Performance>>
Accuracy:  0.8523610280932457
F1 Score:  0.43735763097949887
[[1330   40]
 [ 207   96]]


### Model Stacking

In [ ]:
# 다양한 분류 모델 import
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import ExtraTreesClassifier

In [ ]:
params

{'n_estimators': 300, 'max_depth': 8, 'num_leaves': 16, 'learning_rate': 0.1}

In [ ]:
from vecstack import stacking

models = [ 
    ExtraTreesClassifier(random_state = 42, n_jobs = -1, n_estimators = 300, max_depth = 6), 
    RandomForestClassifier(random_state = 42, n_jobs = -1, n_estimators = 300, max_depth = 6), 
    XGBClassifier(seed = 42, n_jobs = -1, learning_rate = 0.1, n_estimators = 100, max_depth = 6),
    LGBMClassifier(**params, objective='binary', metric='accuracy', random_state=42, verbose=0)
    ]

In [ ]:
S_train, S_test = stacking(models, 
                           X_train_scaled, y_train, X_test_scaled, 
                           regression = False,  # 분류문제라는 의미
                           metric = accuracy_score, 
                           n_folds = 5, stratified = True, shuffle = True,
                           random_state = 42, verbose = 2)

task:         [classification]
n_classes:    [2]
metric:       [accuracy_score]
mode:         [oof_pred_bag]
n_models:     [4]

model  0:     [ExtraTreesClassifier]
    fold  0:  [0.81051479]
    fold  1:  [0.82037240]
    fold  2:  [0.80387144]
    fold  3:  [0.80569759]
    ----
    MEAN:     [0.81011405] + [0.00640058]
    FULL:     [0.81011503]

model  1:     [RandomForestClassifier]


c:\Users\prohe\anaconda3\envs\py38\lib\site-packages\vecstack\core.py:615: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  S_test[:, model_counter] = st.mode(S_test_temp, axis = 1)[0].ravel()


    fold  0:  [0.88024827]
    fold  1:  [0.87331143]
    fold  2:  [0.85208181]
    fold  3:  [0.85829072]
    ----
    MEAN:     [0.86598306] + [0.01128736]
    FULL:     [0.86598503]

model  2:     [XGBClassifier]


c:\Users\prohe\anaconda3\envs\py38\lib\site-packages\vecstack\core.py:615: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  S_test[:, model_counter] = st.mode(S_test_temp, axis = 1)[0].ravel()


    fold  0:  [0.92259949]
    fold  1:  [0.91748813]
    fold  2:  [0.90650110]
    fold  3:  [0.91526662]
    ----
    MEAN:     [0.91546383] + [0.00581775]
    FULL:     [0.91546467]

model  3:     [LGBMClassifier]


c:\Users\prohe\anaconda3\envs\py38\lib\site-packages\vecstack\core.py:615: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  S_test[:, model_counter] = st.mode(S_test_temp, axis = 1)[0].ravel()


    fold  0:  [0.93172691]
    fold  1:  [0.91639284]
    fold  2:  [0.90796202]
    fold  3:  [0.90978817]
    ----
    MEAN:     [0.91646748] + [0.00935163]
    FULL:     [0.91646887]



c:\Users\prohe\anaconda3\envs\py38\lib\site-packages\vecstack\core.py:615: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  S_test[:, model_counter] = st.mode(S_test_temp, axis = 1)[0].ravel()


In [ ]:
model = LGBMClassifier(**params, objective='binary', metric='accuracy', random_state=42, verbose=0)

In [ ]:
model = model.fit(S_train, y_resampled)

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

In [ ]:
y_pred = model.predict(S_test)

In [ ]:
print('Final prediction score: [%.8f]' % accuracy_score(y_test, y_pred))

Final prediction score: [0.85534967]
