In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

# 경고 메시지 출력 표기 생략
warnings.filterwarnings('ignore')

In [2]:
# 데이터 불러오기
mydata = pd.read_csv("https://raw.githubusercontent.com/agtechresearch/LectureAlgorithm/main/csv/married_full.csv")
mydata.head()

gender   age  age_partner  importance_same_religion  \
0  female  21.0         27.0                       4.0   
1  female  21.0         22.0                       4.0   
2  female  21.0         22.0                       4.0   
3  female  21.0         23.0                       4.0   
4  female  21.0         24.0                       4.0   

   pref_of_partner_attractive  pref_of_partner_sincere  \
0                        35.0                     20.0   
1                        60.0                      0.0   
2                        19.0                     18.0   
3                        30.0                      5.0   
4                        30.0                     10.0   

   pref_of_partner_intelligence  pref_of_partner_funny  \
0                          20.0                   20.0   
1                           0.0                   40.0   
2                          19.0                   18.0   
3                          15.0                   40.0   
4                          20.0                   10.0   

   pref_of_partner_ambitious  pref_of_partner_shared_interests  ...  \
0                        0.0                               5.0  ...   
1                        0.0                               0.0  ...   
2                       14.0                              12.0  ...   
3                        5.0                               5.0  ...   
4                       10.0                              20.0  ...   

   my_eval_sincere  my_eval_intelligence  my_eval_funny  my_eval_ambition  \
0              9.0                   7.0            7.0               6.0   
1              8.0                   7.0            8.0               5.0   
2              8.0                   9.0            8.0               5.0   
3              6.0                   8.0            7.0               6.0   
4              6.0                   7.0            7.0               6.0   

   my_eval_shared_interests  interests_correlate  \
0                       5.0                 0.14   
1                       6.0                 0.54   
2                       7.0                 0.16   
3                       8.0                 0.61   
4                       6.0                 0.21   

   expected_happy_with_couple_match  how_much_i_liked  guess_prob_liked  \
0                               3.0               7.0               6.0   
1                               3.0               7.0               5.0   
2                               3.0               7.0               5.0   
3                               3.0               7.0               6.0   
4                               3.0               6.0               6.0   

   married  
0        0  
1        0  
2        1  
3        1  
4        1  

[5 rows x 33 columns]

In [3]:
# 변수가 33개가 있으므로, 모든 변수를 출력하려면 다음과 같이 설정해야 함
pd.options.display.max_columns = 35
mydata.head()

gender   age  age_partner  importance_same_religion  \
0  female  21.0         27.0                       4.0   
1  female  21.0         22.0                       4.0   
2  female  21.0         22.0                       4.0   
3  female  21.0         23.0                       4.0   
4  female  21.0         24.0                       4.0   

   pref_of_partner_attractive  pref_of_partner_sincere  \
0                        35.0                     20.0   
1                        60.0                      0.0   
2                        19.0                     18.0   
3                        30.0                      5.0   
4                        30.0                     10.0   

   pref_of_partner_intelligence  pref_of_partner_funny  \
0                          20.0                   20.0   
1                           0.0                   40.0   
2                          19.0                   18.0   
3                          15.0                   40.0   
4                          20.0                   10.0   

   pref_of_partner_ambitious  pref_of_partner_shared_interests  \
0                        0.0                               5.0   
1                        0.0                               0.0   
2                       14.0                              12.0   
3                        5.0                               5.0   
4                       10.0                              20.0   

   eval_by_partner_attractive  eval_by_partner_sincere  \
0                         6.0                      8.0   
1                         7.0                      8.0   
2                        10.0                     10.0   
3                         7.0                      8.0   
4                         8.0                      7.0   

   eval_by_partner_intelligence  eval_by_partner_funny  \
0                           8.0                    8.0   
1                          10.0                    7.0   
2                          10.0                   10.0   
3                           9.0                    8.0   
4                           9.0                    6.0   

   eval_by_partner_ambitous  eval_by_partner_shared_interests  \
0                       8.0                               6.0   
1                       7.0                               5.0   
2                      10.0                              10.0   
3                       9.0                               8.0   
4                       9.0                               7.0   

   my_pref_attractive  my_pref_sincere  my_pref_intellicence  my_pref_funny  \
0                15.0             20.0                  20.0           15.0   
1                15.0             20.0                  20.0           15.0   
2                15.0             20.0                  20.0           15.0   
3                15.0             20.0                  20.0           15.0   
4                15.0             20.0                  20.0           15.0   

   my_pref_ambtition  my_pref_shared_interests  my_eval_attractive  \
0               15.0                      15.0                 6.0   
1               15.0                      15.0                 7.0   
2               15.0                      15.0                 5.0   
3               15.0                      15.0                 7.0   
4               15.0                      15.0                 5.0   

   my_eval_sincere  my_eval_intelligence  my_eval_funny  my_eval_ambition  \
0              9.0                   7.0            7.0               6.0   
1              8.0                   7.0            8.0               5.0   
2              8.0                   9.0            8.0               5.0   
3              6.0                   8.0            7.0               6.0   
4              6.0                   7.0            7.0               6.0   

   my_eval_shared_interests  interests_correlate  \
0                       5.0                 0.14   
1      

In [4]:
mydata.head()

gender   age  age_partner  importance_same_religion  \
0  female  21.0         27.0                       4.0   
1  female  21.0         22.0                       4.0   
2  female  21.0         22.0                       4.0   
3  female  21.0         23.0                       4.0   
4  female  21.0         24.0                       4.0   

   pref_of_partner_attractive  pref_of_partner_sincere  \
0                        35.0                     20.0   
1                        60.0                      0.0   
2                        19.0                     18.0   
3                        30.0                      5.0   
4                        30.0                     10.0   

   pref_of_partner_intelligence  pref_of_partner_funny  \
0                          20.0                   20.0   
1                           0.0                   40.0   
2                          19.0                   18.0   
3                          15.0                   40.0   
4                          20.0                   10.0   

   pref_of_partner_ambitious  pref_of_partner_shared_interests  \
0                        0.0                               5.0   
1                        0.0                               0.0   
2                       14.0                              12.0   
3                        5.0                               5.0   
4                       10.0                              20.0   

   eval_by_partner_attractive  eval_by_partner_sincere  \
0                         6.0                      8.0   
1                         7.0                      8.0   
2                        10.0                     10.0   
3                         7.0                      8.0   
4                         8.0                      7.0   

   eval_by_partner_intelligence  eval_by_partner_funny  \
0                           8.0                    8.0   
1                          10.0                    7.0   
2                          10.0                   10.0   
3                           9.0                    8.0   
4                           9.0                    6.0   

   eval_by_partner_ambitous  eval_by_partner_shared_interests  \
0                       8.0                               6.0   
1                       7.0                               5.0   
2                      10.0                              10.0   
3                       9.0                               8.0   
4                       9.0                               7.0   

   my_pref_attractive  my_pref_sincere  my_pref_intellicence  my_pref_funny  \
0                15.0             20.0                  20.0           15.0   
1                15.0             20.0                  20.0           15.0   
2                15.0             20.0                  20.0           15.0   
3                15.0             20.0                  20.0           15.0   
4                15.0             20.0                  20.0           15.0   

   my_pref_ambtition  my_pref_shared_interests  my_eval_attractive  \
0               15.0                      15.0                 6.0   
1               15.0                      15.0                 7.0   
2               15.0                      15.0                 5.0   
3               15.0                      15.0                 7.0   
4               15.0                      15.0                 5.0   

   my_eval_sincere  my_eval_intelligence  my_eval_funny  my_eval_ambition  \
0              9.0                   7.0            7.0               6.0   
1              8.0                   7.0            8.0               5.0   
2              8.0                   9.0            8.0               5.0   
3              6.0                   8.0            7.0               6.0   
4              6.0                   7.0            7.0               6.0   

   my_eval_shared_interests  interests_correlate  \
0                       5.0                 0.14   
1      

### 필요한거 말고 여러 열을 제거하자


In [5]:

# mydata = mydata[['eval_by_partner_attractive','eval_by_partner_sincere','eval_by_partner_intelligence','eval_by_partner_funny','eval_by_partner_ambitous','eval_by_partner_shared_interests',
#                  'my_eval_attractive','my_eval_sincere','my_eval_intelligence','my_eval_funny','my_eval_ambition','my_eval_shared_interests','how_much_i_liked','guess_prob_liked','married']]

In [5]:
mydata = mydata.drop(['gender'],axis=1)

### train/ test로 균일하게 나눠보자

In [6]:
from sklearn.model_selection import StratifiedShuffleSplit

split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in split.split(mydata, mydata['married']):
    sss_train_set = mydata.loc[train_index]
    sss_test_set = mydata.loc[test_index]

In [80]:
X_train = sss_train_set.drop("married", axis=1)
y_train = sss_train_set["married"].copy()

X_test = sss_test_set.drop("married", axis=1)
y_test = sss_test_set["married"].copy()

### 모든 결측치를 knn으로 채우고 오버 샘플링을 통해 그 값을 높여보자

In [ ]:
# 결측치 median값으로 채우기
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy="median")
imputer.fit(X_train)
X_train = imputer.transform(X_train)
X_test = imputer.transform(X_test)

In [81]:
# 결측치 knn으로 채우기
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=2)
X_train = imputer.fit_transform(X_train)
X_test = imputer.fit_transform(X_test)


In [82]:
# #표준화 시키기
from sklearn.preprocessing import StandardScaler
X_train_scaled = StandardScaler().fit_transform(X_train)
X_test_scaled = StandardScaler().fit_transform(X_test)

In [83]:
X_train_scaled

array([[ 0.46354821, -0.65185945,  1.9175639 , ..., -0.30895567,
        -1.17389284, -1.53308965],
       [-0.38282111,  1.87657655,  1.56003341, ...,  0.26462315,
        -0.07947191, -0.58177301],
       [ 0.46354821, -0.93279679,  0.84497244, ...,  0.26462315,
        -0.07947191, -0.10611469],
       ...,
       [ 0.18142511, -1.21373412, -0.22761901, ..., -0.30895567,
         0.46773855,  0.84520196],
       [-0.38282111,  2.15751388, -0.94267998, ...,  0.26462315,
        -0.07947191,  0.36954364],
       [ 0.18142511, -0.93279679,  1.56003341, ...,  1.4117808 ,
        -0.07947191, -0.58177301]])

In [84]:
from imblearn.combine import SMOTETomek
from imblearn.under_sampling import TomekLinks

smoteto = SMOTETomek(tomek=TomekLinks(sampling_strategy='majority'))
X_resampled, y_resampled = smoteto.fit_resample(X_train_scaled, y_train)


In [85]:
X_resampled.shape, y_resampled.shape

((10951, 31), (10951,))

In [86]:
# 베이지안 최적화
from lightgbm import LGBMClassifier
from sklearn.metrics import accuracy_score

param_bounds = {
    'n_estimators': (100, 500),
    'max_depth': (3, 10),
    'num_leaves': (20, 100),
    'min_child_samples': (10, 30),
    'learning_rate': (0.01, 0.3),
    'scale_pos_weight': (1, 2),
}

def eval_function(n_estimators, max_depth, num_leaves, min_child_samples, learning_rate, scale_pos_weight):
    params = {
        'n_estimators': int(n_estimators),
        'max_depth': int(max_depth),
        'num_leaves': int(num_leaves),
        'min_child_samples': int(min_child_samples),
        'learning_rate': learning_rate,
        'scale_pos_weight': scale_pos_weight,
    }
    lgbm = LGBMClassifier(**params, objective='binary', metric='accuracy', random_state=42, verbose=0)

    lgbm.fit(X_train_scaled, y_train)
    y_pred = lgbm.predict(X_test_scaled)
    acc = accuracy_score(y_test, y_pred)
    return acc

In [87]:
from bayes_opt import BayesianOptimization

optimizer = BayesianOptimization(f=eval_function, pbounds=param_bounds, random_state=42)
optimizer.maximize(init_points=5, n_iter=10)

|   iter    |  target   | learni... | max_depth | min_ch... | n_esti... | num_le... | scale_... |
-------------------------------------------------------------------------------------------------
| 1         | 0.853     | 0.1186    | 9.655     | 24.64     | 339.5     | 32.48     | 1.156     |
| 2         | 0.838     | 0.02684   | 9.063     | 22.02     | 383.2     | 21.65     | 1.97      |
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGB

In [88]:
# 최적화된 하이퍼파라미터로 모델 재학습
best_params = {
    'n_estimators': round(optimizer.max['params']['n_estimators']),
    'max_depth': round(optimizer.max['params']['max_depth']),
    'num_leaves': round(optimizer.max['params']['num_leaves']),
    'min_child_samples': round(optimizer.max['params']['min_child_samples']),
    'learning_rate': optimizer.max['params']['learning_rate'],
    'scale_pos_weight': optimizer.max['params']['scale_pos_weight'],
}

best_lgbm = LGBMClassifier(**best_params, objective='binary', metric='accuracy', random_state=42, verbose=0)
best_lgbm.fit(X_train_scaled, y_train)

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

LGBMClassifier(learning_rate=0.18514766177530592, max_depth=8,
               metric='accuracy', min_child_samples=12, n_estimators=306,
               num_leaves=65, objective='binary', random_state=42,
               scale_pos_weight=1.1213132598501234, verbose=0)

In [89]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

# Train data 성능 평가
y_train_pred = best_lgbm.predict(X_train_scaled)
print("<<Train Set Performance>>")
print("Accuracy: ", accuracy_score(y_train, y_train_pred))
print("F1 Score: ", f1_score(y_train, y_train_pred))
print(confusion_matrix(y_train, y_train_pred))

# Test data 성능 평가
y_test_pred = best_lgbm.predict(X_test_scaled)
print("<<Test Set Performance>>")
print("Accuracy: ", accuracy_score(y_test, y_test_pred))
print("F1 Score: ", f1_score(y_test, y_test_pred))
print(confusion_matrix(y_test, y_test_pred))

<<Train Set Performance>>
Accuracy:  1.0
F1 Score:  1.0
[[5479    0]
 [   0 1210]]
<<Test Set Performance>>
Accuracy:  0.8511655708308428
F1 Score:  0.49287169042769857
[[1303   67]
 [ 182  121]]


In [90]:
# xgboost 모델 학습
from xgboost import XGBClassifier
xgb = XGBClassifier(n_estimators=300, max_depth=8, learning_rate=0.1, objective='binary:logistic', random_state=42)
xgb.fit(X_train_scaled, y_train)


[21:43:33] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.1, max_delta_step=0,
              max_depth=8, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=300, n_jobs=8,
              num_parallel_tree=1, predictor='auto', random_state=42,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [91]:
y_train_pred = xgb.predict(X_train_scaled)
print("<<Train Set Performance>>")
print("Accuracy: ", accuracy_score(y_train, y_train_pred))
print("F1 Score: ", f1_score(y_train, y_train_pred))
print(confusion_matrix(y_train, y_train_pred))

<<Train Set Performance>>
Accuracy:  1.0
F1 Score:  1.0
[[5479    0]
 [   0 1210]]


In [92]:
y_test_pred = xgb.predict(X_test_scaled)
print("<<Test Set Performance>>")
print("Accuracy: ", accuracy_score(y_test, y_test_pred))
print("F1 Score: ", f1_score(y_test, y_test_pred))
print(confusion_matrix(y_test, y_test_pred))

<<Test Set Performance>>
Accuracy:  0.8511655708308428
F1 Score:  0.48232848232848236
[[1308   62]
 [ 187  116]]


In [93]:
param_bounds = {
    'n_estimators': (100, 500),
    'max_depth': (3, 10),
    'num_leaves': (20, 100),
    'min_child_samples': (10, 30),
    'learning_rate': (0.01, 0.3),
    'scale_pos_weight': (1, 2),
}

def eval_function(n_estimators, max_depth, num_leaves, min_child_samples, learning_rate, scale_pos_weight):
    params = {
        'n_estimators': int(n_estimators),
        'max_depth': int(max_depth),
        'num_leaves': int(num_leaves),
        'min_child_samples': int(min_child_samples),
        'learning_rate': learning_rate,
        'scale_pos_weight': scale_pos_weight,
    }
    lgbm = LGBMClassifier(**params, objective='binary', metric='accuracy', random_state=42, verbose=0)

    lgbm.fit(X_train_scaled, y_train)
    y_pred = lgbm.predict(X_test_scaled)
    acc = accuracy_score(y_test, y_pred)
    return acc

In [94]:
from bayes_opt import BayesianOptimization

optimizer = BayesianOptimization(f=eval_function, pbounds=param_bounds, random_state=42)
optimizer.maximize(init_points=5, n_iter=10)

|   iter    |  target   | learni... | max_depth | min_ch... | n_esti... | num_le... | scale_... |
-------------------------------------------------------------------------------------------------
| 1         | 0.853     | 0.1186    | 9.655     | 24.64     | 339.5     | 32.48     | 1.156     |


| 2         | 0.838     | 0.02684   | 9.063     | 22.02     | 383.2     | 21.65     | 1.97      |
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[L

In [95]:
best_params = {
    'n_estimators': round(optimizer.max['params']['n_estimators']),
    'max_depth': round(optimizer.max['params']['max_depth']),
    'num_leaves': round(optimizer.max['params']['num_leaves']),
    'min_child_samples': round(optimizer.max['params']['min_child_samples']),
    'learning_rate': optimizer.max['params']['learning_rate'],
    'scale_pos_weight': optimizer.max['params']['scale_pos_weight'],
}

best_lgbm = LGBMClassifier(**best_params, objective='binary', metric='accuracy', random_state=42, verbose=0)
best_lgbm.fit(X_train_scaled, y_train)

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

LGBMClassifier(learning_rate=0.18514766177530592, max_depth=8,
               metric='accuracy', min_child_samples=12, n_estimators=306,
               num_leaves=65, objective='binary', random_state=42,
               scale_pos_weight=1.1213132598501234, verbose=0)

In [96]:
# Train data 성능 평가
y_train_pred = best_lgbm.predict(X_train_scaled)
print("<<Train Set Performance>>")
print("Accuracy: ", accuracy_score(y_train, y_train_pred))
print("F1 Score: ", f1_score(y_train, y_train_pred))
print(confusion_matrix(y_train, y_train_pred))

# Test data 성능 평가
y_test_pred = best_lgbm.predict(X_test_scaled)
print("<<Test Set Performance>>")
print("Accuracy: ", accuracy_score(y_test, y_test_pred))
print("F1 Score: ", f1_score(y_test, y_test_pred))
print(confusion_matrix(y_test, y_test_pred))

<<Train Set Performance>>
Accuracy:  1.0
F1 Score:  1.0
[[5479    0]
 [   0 1210]]
<<Test Set Performance>>
Accuracy:  0.8511655708308428
F1 Score:  0.49287169042769857
[[1303   67]
 [ 182  121]]


In [97]:
from sklearn.svm import SVC

svc = SVC(kernel='rbf', C=10, gamma='scale', class_weight='balanced', random_state=42)
svc.fit(X_train_scaled, y_train)

SVC(C=10, class_weight='balanced', random_state=42)

In [ ]:
# Train data 성능 평가
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

y_train_pred = best_svc.predict(X_train_scaled)
print("<<Train Set Performance>>")
print("Accuracy: ", accuracy_score(y_train, y_train_pred))
print("F1 Score: ", f1_score(y_train, y_train_pred))
print(confusion_matrix(y_train, y_train_pred))

# Test data 성능 평가
y_test_pred = best_svc.predict(X_test_scaled)
print("<<Test Set Performance>>")
print("Accuracy: ", accuracy_score(y_test, y_test_pred))
print("F1 Score: ", f1_score(y_test, y_test_pred))
print(confusion_matrix(y_test, y_test_pred))

<<Train Set Performance>>
Accuracy:  0.9997010016444909
F1 Score:  0.9991742361684558
[[5477    2]
 [   0 1210]]
<<Test Set Performance>>
Accuracy:  0.8457860131500299
F1 Score:  0.48192771084337355
[[1295   75]
 [ 183  120]]
