In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

# 경고 메시지 출력 표기 생략
warnings.filterwarnings('ignore')

In [90]:
# 데이터 불러오기
mydata = pd.read_csv("https://raw.githubusercontent.com/agtechresearch/LectureAlgorithm/main/csv/married_full.csv")
mydata.head()

gender   age  age_partner  importance_same_religion  \
0  female  21.0         27.0                       4.0   
1  female  21.0         22.0                       4.0   
2  female  21.0         22.0                       4.0   
3  female  21.0         23.0                       4.0   
4  female  21.0         24.0                       4.0   

   pref_of_partner_attractive  pref_of_partner_sincere  \
0                        35.0                     20.0   
1                        60.0                      0.0   
2                        19.0                     18.0   
3                        30.0                      5.0   
4                        30.0                     10.0   

   pref_of_partner_intelligence  pref_of_partner_funny  \
0                          20.0                   20.0   
1                           0.0                   40.0   
2                          19.0                   18.0   
3                          15.0                   40.0   
4                          20.0                   10.0   

   pref_of_partner_ambitious  pref_of_partner_shared_interests  \
0                        0.0                               5.0   
1                        0.0                               0.0   
2                       14.0                              12.0   
3                        5.0                               5.0   
4                       10.0                              20.0   

   eval_by_partner_attractive  eval_by_partner_sincere  \
0                         6.0                      8.0   
1                         7.0                      8.0   
2                        10.0                     10.0   
3                         7.0                      8.0   
4                         8.0                      7.0   

   eval_by_partner_intelligence  eval_by_partner_funny  \
0                           8.0                    8.0   
1                          10.0                    7.0   
2                          10.0                   10.0   
3                           9.0                    8.0   
4                           9.0                    6.0   

   eval_by_partner_ambitous  eval_by_partner_shared_interests  \
0                       8.0                               6.0   
1                       7.0                               5.0   
2                      10.0                              10.0   
3                       9.0                               8.0   
4                       9.0                               7.0   

   my_pref_attractive  my_pref_sincere  my_pref_intellicence  my_pref_funny  \
0                15.0             20.0                  20.0           15.0   
1                15.0             20.0                  20.0           15.0   
2                15.0             20.0                  20.0           15.0   
3                15.0             20.0                  20.0           15.0   
4                15.0             20.0                  20.0           15.0   

   my_pref_ambtition  my_pref_shared_interests  my_eval_attractive  \
0               15.0                      15.0                 6.0   
1               15.0                      15.0                 7.0   
2               15.0                      15.0                 5.0   
3               15.0                      15.0                 7.0   
4               15.0                      15.0                 5.0   

   my_eval_sincere  my_eval_intelligence  my_eval_funny  my_eval_ambition  \
0              9.0                   7.0            7.0               6.0   
1              8.0                   7.0            8.0               5.0   
2              8.0                   9.0            8.0               5.0   
3              6.0                   8.0            7.0               6.0   
4              6.0                   7.0            7.0               6.0   

   my_eval_shared_interests  interests_correlate  \
0                       5.0                 0.14   
1      

In [91]:
# 변수가 33개가 있으므로, 모든 변수를 출력하려면 다음과 같이 설정해야 함
pd.options.display.max_columns = 35
mydata.head()

gender   age  age_partner  importance_same_religion  \
0  female  21.0         27.0                       4.0   
1  female  21.0         22.0                       4.0   
2  female  21.0         22.0                       4.0   
3  female  21.0         23.0                       4.0   
4  female  21.0         24.0                       4.0   

   pref_of_partner_attractive  pref_of_partner_sincere  \
0                        35.0                     20.0   
1                        60.0                      0.0   
2                        19.0                     18.0   
3                        30.0                      5.0   
4                        30.0                     10.0   

   pref_of_partner_intelligence  pref_of_partner_funny  \
0                          20.0                   20.0   
1                           0.0                   40.0   
2                          19.0                   18.0   
3                          15.0                   40.0   
4                          20.0                   10.0   

   pref_of_partner_ambitious  pref_of_partner_shared_interests  \
0                        0.0                               5.0   
1                        0.0                               0.0   
2                       14.0                              12.0   
3                        5.0                               5.0   
4                       10.0                              20.0   

   eval_by_partner_attractive  eval_by_partner_sincere  \
0                         6.0                      8.0   
1                         7.0                      8.0   
2                        10.0                     10.0   
3                         7.0                      8.0   
4                         8.0                      7.0   

   eval_by_partner_intelligence  eval_by_partner_funny  \
0                           8.0                    8.0   
1                          10.0                    7.0   
2                          10.0                   10.0   
3                           9.0                    8.0   
4                           9.0                    6.0   

   eval_by_partner_ambitous  eval_by_partner_shared_interests  \
0                       8.0                               6.0   
1                       7.0                               5.0   
2                      10.0                              10.0   
3                       9.0                               8.0   
4                       9.0                               7.0   

   my_pref_attractive  my_pref_sincere  my_pref_intellicence  my_pref_funny  \
0                15.0             20.0                  20.0           15.0   
1                15.0             20.0                  20.0           15.0   
2                15.0             20.0                  20.0           15.0   
3                15.0             20.0                  20.0           15.0   
4                15.0             20.0                  20.0           15.0   

   my_pref_ambtition  my_pref_shared_interests  my_eval_attractive  \
0               15.0                      15.0                 6.0   
1               15.0                      15.0                 7.0   
2               15.0                      15.0                 5.0   
3               15.0                      15.0                 7.0   
4               15.0                      15.0                 5.0   

   my_eval_sincere  my_eval_intelligence  my_eval_funny  my_eval_ambition  \
0              9.0                   7.0            7.0               6.0   
1              8.0                   7.0            8.0               5.0   
2              8.0                   9.0            8.0               5.0   
3              6.0                   8.0            7.0               6.0   
4              6.0                   7.0            7.0               6.0   

   my_eval_shared_interests  interests_correlate  \
0                       5.0                 0.14   
1      

In [92]:
mydata.head()

gender   age  age_partner  importance_same_religion  \
0  female  21.0         27.0                       4.0   
1  female  21.0         22.0                       4.0   
2  female  21.0         22.0                       4.0   
3  female  21.0         23.0                       4.0   
4  female  21.0         24.0                       4.0   

   pref_of_partner_attractive  pref_of_partner_sincere  \
0                        35.0                     20.0   
1                        60.0                      0.0   
2                        19.0                     18.0   
3                        30.0                      5.0   
4                        30.0                     10.0   

   pref_of_partner_intelligence  pref_of_partner_funny  \
0                          20.0                   20.0   
1                           0.0                   40.0   
2                          19.0                   18.0   
3                          15.0                   40.0   
4                          20.0                   10.0   

   pref_of_partner_ambitious  pref_of_partner_shared_interests  \
0                        0.0                               5.0   
1                        0.0                               0.0   
2                       14.0                              12.0   
3                        5.0                               5.0   
4                       10.0                              20.0   

   eval_by_partner_attractive  eval_by_partner_sincere  \
0                         6.0                      8.0   
1                         7.0                      8.0   
2                        10.0                     10.0   
3                         7.0                      8.0   
4                         8.0                      7.0   

   eval_by_partner_intelligence  eval_by_partner_funny  \
0                           8.0                    8.0   
1                          10.0                    7.0   
2                          10.0                   10.0   
3                           9.0                    8.0   
4                           9.0                    6.0   

   eval_by_partner_ambitous  eval_by_partner_shared_interests  \
0                       8.0                               6.0   
1                       7.0                               5.0   
2                      10.0                              10.0   
3                       9.0                               8.0   
4                       9.0                               7.0   

   my_pref_attractive  my_pref_sincere  my_pref_intellicence  my_pref_funny  \
0                15.0             20.0                  20.0           15.0   
1                15.0             20.0                  20.0           15.0   
2                15.0             20.0                  20.0           15.0   
3                15.0             20.0                  20.0           15.0   
4                15.0             20.0                  20.0           15.0   

   my_pref_ambtition  my_pref_shared_interests  my_eval_attractive  \
0               15.0                      15.0                 6.0   
1               15.0                      15.0                 7.0   
2               15.0                      15.0                 5.0   
3               15.0                      15.0                 7.0   
4               15.0                      15.0                 5.0   

   my_eval_sincere  my_eval_intelligence  my_eval_funny  my_eval_ambition  \
0              9.0                   7.0            7.0               6.0   
1              8.0                   7.0            8.0               5.0   
2              8.0                   9.0            8.0               5.0   
3              6.0                   8.0            7.0               6.0   
4              6.0                   7.0            7.0               6.0   

   my_eval_shared_interests  interests_correlate  \
0                       5.0                 0.14   
1      

### 필요한거 말고 여러 열을 제거하자


In [93]:

mydata = mydata[['eval_by_partner_attractive','eval_by_partner_sincere','eval_by_partner_intelligence','eval_by_partner_funny','eval_by_partner_ambitous','eval_by_partner_shared_interests',
                 'my_eval_attractive','my_eval_sincere','my_eval_intelligence','my_eval_funny','my_eval_ambition','my_eval_shared_interests','how_much_i_liked','guess_prob_liked','married']]

In [94]:
mydata.shape

(8362, 15)

### train/ test로 균일하게 나눠보자

In [95]:
from sklearn.model_selection import StratifiedShuffleSplit

split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in split.split(mydata, mydata['married']):
    sss_train_set = mydata.loc[train_index]
    sss_test_set = mydata.loc[test_index]

In [96]:
X_train = sss_train_set.drop("married", axis=1)
y_train = sss_train_set["married"].copy()

X_test = sss_test_set.drop("married", axis=1)
y_test = sss_test_set["married"].copy()

In [97]:
# X_train_scaled = pd.DataFrame(X_train_scaled, columns=X_train.columns)
# X_test_scaled = pd.DataFrame(X_test_scaled, columns=X_test.columns)

In [ ]:
# X_train_scaled = pd.DataFrame(X_train_scaled, columns=X_train.columns)
# X_test_scaled = pd.DataFrame(X_test_scaled, columns=X_test.columns)

In [98]:
X_train_scaled = X_train
X_test_scaled = X_test

### 모든 결측치를 knn으로 채우고 오버 샘플링을 통해 그 값을 높여보자

In [99]:
# 결측치 knn으로 채우기
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=2)
X_train_scaled = imputer.fit_transform(X_train_scaled)
X_test_scaled = imputer.fit_transform(X_test_scaled)


In [100]:
# #표준화 시키기
from sklearn.preprocessing import StandardScaler
X_train_scaled = StandardScaler().fit_transform(X_train)
X_test_scaled = StandardScaler().fit_transform(X_test)

In [101]:
# X_train_scaled = pd.DataFrame(X_train_scaled, columns=X_train.columns)
# X_test_scaled = pd.DataFrame(X_test_scaled, columns=X_test.columns)

In [102]:
# X_train_scaled 결측치 확인
# X_train_scaled.isnull().sum()

In [103]:
# X_train_scaled 오버 샘플링
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_train_scaled, y_train = smote.fit_resample(X_train_scaled, y_train)


ValueError: Input X contains NaN.
SMOTE does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [ ]:
X_train_scaled.shape

(10958, 14)

In [ ]:
# lightgbm 모델 학습
from lightgbm import LGBMClassifier

params = {
    'n_estimators': 300,        #* 반복 수행하려는 트리의 개수 (너무 크면 오버피팅 발생)
    'max_depth': 8,             #* 트리의 최대 깊이 (너무 크면 오버피팅 발생)   # 보통 3~12(가장 민감하므로 먼저 튜닝해야할 값) # lightgbm처럼 leaf-wise로 학습하는 경우 끝까지(-1)도 괜찮다고 한다.
    # 'boosting_type' = 'gbdt'  # 부스팅 타입 (gbdt: Gradient Boosting Decision Tree, rf: RandomForest)
    'num_leaves': 16,           #* 하나의 트리가 가질 수 있는 최대 리프 수 (2번째로 민감. max_depth와 함께 튜닝)
    'learning_rate': 0.1,       # 부스팅 스탭 반복할 때 학습률(0~1) #튜닝시 0.1~0.3, 최종 모형은 0.05 이하
}

lgbm = LGBMClassifier(**params, objective='binary', metric='accuracy', random_state=42, verbose=0)
lgbm.fit(X_train_scaled, y_train)


LGBMClassifier(max_depth=8, metric='accuracy', n_estimators=300, num_leaves=16,
               objective='binary', random_state=42, verbose=0)

In [ ]:
# Train data 성능 평가
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

y_train_pred = lgbm.predict(X_train_scaled)
print("<<Train Set Performance>>")
print("Accuracy: ", accuracy_score(y_train, y_train_pred))
print("F1 Score: ", f1_score(y_train, y_train_pred))
print(confusion_matrix(y_train, y_train_pred))

<<Train Set Performance>>
Accuracy:  0.9479832086147107
F1 Score:  0.9464989675239347
[[5346  133]
 [ 437 5042]]


In [ ]:
# Test data 성능 평가
y_test_pred = lgbm.predict(X_test_scaled)
print("<<Test Set Performance>>")
print("Accuracy: ", accuracy_score(y_test, y_test_pred))
print("F1 Score: ", f1_score(y_test, y_test_pred))
print(confusion_matrix(y_test, y_test_pred))

<<Test Set Performance>>
Accuracy:  0.2749551703526599
F1 Score:  0.33241607044578975
[[ 158 1212]
 [   1  302]]


In [ ]:
# xgboost 모델 학습
from xgboost import XGBClassifier
xgb = XGBClassifier(n_estimators=300, max_depth=8, learning_rate=0.1, objective='binary:logistic', random_state=42)
xgb.fit(X_train_scaled, y_train)


[21:10:21] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.1, max_delta_step=0,
              max_depth=8, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=300, n_jobs=8,
              num_parallel_tree=1, predictor='auto', random_state=42,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [ ]:
y_train_pred = xgb.predict(X_train_scaled)
print("<<Train Set Performance>>")
print("Accuracy: ", accuracy_score(y_train, y_train_pred))
print("F1 Score: ", f1_score(y_train, y_train_pred))
print(confusion_matrix(y_train, y_train_pred))

<<Train Set Performance>>
Accuracy:  0.9943420332177405
F1 Score:  0.9943285766556897
[[5461   18]
 [  44 5435]]


In [ ]:
y_test_pred = xgb.predict(X_test_scaled)
print("<<Test Set Performance>>")
print("Accuracy: ", accuracy_score(y_test, y_test_pred))
print("F1 Score: ", f1_score(y_test, y_test_pred))
print(confusion_matrix(y_test, y_test_pred))

<<Test Set Performance>>
Accuracy:  0.3239689181111775
F1 Score:  0.3458646616541354
[[ 243 1127]
 [   4  299]]


In [87]:
param_bounds = {
    'n_estimators': (100, 500),
    'max_depth': (3, 10),
    'num_leaves': (20, 100),
    'min_child_samples': (10, 30),
    'learning_rate': (0.01, 0.3),
    'scale_pos_weight': (1, 2),
}

def eval_function(n_estimators, max_depth, num_leaves, min_child_samples, learning_rate, scale_pos_weight):
    params = {
        'n_estimators': int(n_estimators),
        'max_depth': int(max_depth),
        'num_leaves': int(num_leaves),
        'min_child_samples': int(min_child_samples),
        'learning_rate': learning_rate,
        'scale_pos_weight': scale_pos_weight,
    }
    lgbm = LGBMClassifier(**params, objective='binary', metric='accuracy', random_state=42, verbose=0)

    lgbm.fit(X_train_scaled, y_train)
    y_pred = lgbm.predict(X_test_scaled)
    acc = accuracy_score(y_test, y_pred)
    return acc

In [88]:
from bayes_opt import BayesianOptimization

optimizer = BayesianOptimization(f=eval_function, pbounds=param_bounds, random_state=42)
optimizer.maximize(init_points=5, n_iter=10)

|   iter    |  target   | learni... | max_depth | min_ch... | n_esti... | num_le... | scale_... |
-------------------------------------------------------------------------------------------------


ValueError: Found input variables with inconsistent numbers of samples: [10958, 6689]

In [ ]:
best_params = {
    'n_estimators': round(optimizer.max['params']['n_estimators']),
    'max_depth': round(optimizer.max['params']['max_depth']),
    'num_leaves': round(optimizer.max['params']['num_leaves']),
    'min_child_samples': round(optimizer.max['params']['min_child_samples']),
    'learning_rate': optimizer.max['params']['learning_rate'],
    'scale_pos_weight': optimizer.max['params']['scale_pos_weight'],
}

best_lgbm = LGBMClassifier(**best_params, objective='binary', metric='accuracy', random_state=42, verbose=0)
best_lgbm.fit(X_train_scaled, y_train)

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

LGBMClassifier(learning_rate=0.14642510579988977, max_depth=10,
               metric='accuracy', min_child_samples=11, n_estimators=500,
               num_leaves=99, objective='binary', random_state=42,
               scale_pos_weight=1.3697364033154678, verbose=0)

In [89]:
# Train data 성능 평가
y_train_pred = best_lgbm.predict(X_train_scaled)
print("<<Train Set Performance>>")
print("Accuracy: ", accuracy_score(y_train, y_train_pred))
print("F1 Score: ", f1_score(y_train, y_train_pred))
print(confusion_matrix(y_train, y_train_pred))

# Test data 성능 평가
y_test_pred = best_lgbm.predict(X_test_scaled)
print("<<Test Set Performance>>")
print("Accuracy: ", accuracy_score(y_test, y_test_pred))
print("F1 Score: ", f1_score(y_test, y_test_pred))
print(confusion_matrix(y_test, y_test_pred))

NameError: name 'best_lgbm' is not defined

In [85]:
from sklearn.svm import SVC

svc = SVC(kernel='rbf', C=10, gamma='scale', class_weight='balanced', random_state=42)
svc.fit(X_train_scaled, y_train)

SVC(C=10, class_weight='balanced', random_state=42)

In [86]:
param_bounds = {
    'C': (0.1, 10),
    'gamma': (0.1, 10),
    }

def eval_function(C, gamma):

    svc = SVC(kernel='rbf', C=C, gamma=gamma, class_weight='balanced', random_state=42)
    svc.fit(X_train_scaled, y_train)
    y_pred = svc.predict(X_test_scaled)
    acc = accuracy_score(y_test, y_pred)
    return acc

In [87]:
from bayes_opt import BayesianOptimization

optimizer = BayesianOptimization(f=eval_function, pbounds=param_bounds, random_state=42)
optimizer.maximize(init_points=5, n_iter=10)

|   iter    |  target   |     C     |   gamma   |
-------------------------------------------------
| 1         | 0.8189    | 3.808     | 9.512     |
| 2         | 0.8189    | 7.347     | 6.027     |
| 3         | 0.8189    | 1.645     | 1.644     |
| 4         | 0.8189    | 0.675     | 8.675     |
| 5         | 0.8189    | 6.051     | 7.11      |
| 6         | 0.8189    | 6.762     | 5.355     |
| 7         | 0.8458    | 9.984     | 0.104     |
| 8         | 0.8428    | 8.091     | 0.1       |
| 9         | 0.8189    | 10.0      | 1.152     |


KeyboardInterrupt: 

In [88]:
best_params = optimizer.max['params']

best_svc = SVC(**best_params, kernel='rbf', class_weight='balanced', random_state=42)
best_svc.fit(X_train_scaled, y_train)

SVC(C=9.983976999460424, class_weight='balanced', gamma=0.10395695663431681,
    random_state=42)

In [89]:
# Train data 성능 평가
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

y_train_pred = best_svc.predict(X_train_scaled)
print("<<Train Set Performance>>")
print("Accuracy: ", accuracy_score(y_train, y_train_pred))
print("F1 Score: ", f1_score(y_train, y_train_pred))
print(confusion_matrix(y_train, y_train_pred))

# Test data 성능 평가
y_test_pred = best_svc.predict(X_test_scaled)
print("<<Test Set Performance>>")
print("Accuracy: ", accuracy_score(y_test, y_test_pred))
print("F1 Score: ", f1_score(y_test, y_test_pred))
print(confusion_matrix(y_test, y_test_pred))

<<Train Set Performance>>
Accuracy:  0.9997010016444909
F1 Score:  0.9991742361684558
[[5477    2]
 [   0 1210]]
<<Test Set Performance>>
Accuracy:  0.8457860131500299
F1 Score:  0.48192771084337355
[[1295   75]
 [ 183  120]]
